# Generated by Django 4.1.1 on 2022-09-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationrequest',
            options={'ordering': ['created']},
        ),
    ]
