# Generated by Django 4.1.1 on 2022-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certificationrequest_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificationrequest',
            constraint=models.UniqueConstraint(fields=('user', 'competence'), name='unique_certification'),
        ),
    ]
