# Generated by Django 4.1.1 on 2022-09-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('MEDICAL', 'Medical'), ('TRANSPORT', 'Transport'), ('FOOD', 'Food'), ('SHELTER', 'Shelter')], max_length=20)),
                ('description', models.TextField()),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refugee_help_request', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='volunteer_help_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
