# Generated by Django 4.1.1 on 2022-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
